### PR TITLE
Upgrade to Blacklight 8.0.0.beta.x

### PR DESCRIPTION
**Pull request by maxkadel**
- Pros
  - Look and feel of app is preserved
  - Logging in and out works
  - Basic search works
  - Facet look and function look good

- Issues resolved:
  - Modals do not display (the current display of modals on main is wonky - see #325
  - When you add a bookmark the bookmark-counter goes up, but then when you go to /bookmarks it says "You have no bookmarks"
  - After re-starting the rails server, the modal partial overlays the entire screen making it so that it cannot be interacted with

### CODE REVIEW

**Comment by christinach** [comment]
@sandbergja and I deployed to staging and did a QA on the UI. 
1. Search results is missing 'You searched for:'
2. 'Quick Links' are missing
3. Modal close button is not visible. This is an exisitng issue in production. The difference is: In production a user can close the modal when clicking outside of the modal or using the escape button. In the blacklight 8 PR only escape works.

@kevinreiss which of the above issues needs to be fixed in order to merge this PR? From our perspective 2 and 3 should be fixed as part of this PR.

**Comment by kevinreiss** [comment]
I agree 1 is not essential.

**Comment by maxkadel** [comment]
I think the first point was introduced in https://github.com/pulibrary/DSS/pull/322/files in changing to the constraints component. From what I could tell, the "You searched for" was intended to be screen-reader only, and the component re-introduced this behavior. I think we could make it visible again by changing the classes on https://github.com/pulibrary/DSS/blob/db39167113a174767037e0d85c12e2dc7e2c59d2/app/components/dss/constraints_component.html.erb#L9

**Review by kevinreiss — APPROVED** [review]
Before merging could we rebase could we rebase/squash the commit but preserve the individual comments.

**Comment by maxkadel** [comment]
After upgrade to beta5 release, the close button on the modal does not work on dss-staging

**Pull request merged**
